# Perform the EOS Virtual Router tasks under Ansible 2.1 or earlier
# using the Ansible eos_template module

- name: Arista EOS Virtual Router Mac Address (Ansible <= 2.1)
  eos_template:
    src: varp_mac_addr.j2
    include_defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: 'cli'
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  when: virtual_mac_addr is defined

- name: Arista EOS VARP VLAN resources (Ansible <= 2.1)
  eos_template:
    src: varp.j2
    include_defaults: true
    config: "{{ _eos_config | default(omit) }}"
    auth_pass: "{{ auth_pass | default(omit) }}"
    authorize: "{{ authorize | default(omit) }}"
    host: "{{ host | default(omit) }}"
    password: "{{ password | default(omit) }}"
    port: "{{ port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    transport: 'cli'
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ username | default(omit) }}"
  notify: save running config
  with_items: "{{ varp_interfaces | default([]) }}"
